import { TablePaginationConfig } from 'antd';
import { FilterValue } from 'antd/es/table/interface';

export type QueryOptions = {
  page?: number;
  limit?: number;
  offset?: number;
  search?: string;
  sortOrder?: 'DESC' | 'ASC' | 'desc' | 'asc';
  sortField?: string;
  pageSize?: number;
  pagination?: TablePaginationConfig;
  sorter?: { columnKey?: string; field?: string; order?: string };
  filters?: Record<string, FilterValue | null>;
  assignee?: string;
  actionState?: 'EXPIRED' | 'DUE' | 'STILL_VALID' | '';
  createdAfter?: string;
  createdBefore?: string;
  route?: string;
  type?: string;
  flag?: string;
  level?: string;
  province?: string;
  district?: string;
  branchId?: string;
  username?: string;
  role?: string;
  code?: string;
  permissionName?: string;
  status?: boolean;
  groupName?: string;
  fullName?: string;
  projectId?: number;
  step?: string;
  name?: string;
  createdAt?: string;
  updatedAt?: string;
  'action-code'?: 'RETURN' | 'SUBMIT';
  processState?: 'UNCLAIM' | 'CLAIM' | '';
  processId?: string;
  'group-code'?: string;
  'group-name'?: string;
  'branch-id'?: string;
  childCode?: string;
  parentCode?: string;
  relationshipCode?: string;
  processType?: string;
  year?: string;
  stepCode?: string;
  branchCode?: string;
  currentStep?: string;
  businessKey?: string;
  group?: string;
};

export type ParamLogin = {
  username: string;
  password: string;
};
