export enum TYPE_COMPONENT {
  LAYOUT = 'LAYOUT',
  MODAL = 'MODAL',
  INPUT = 'INPUT',
  TEXTAREA = 'TEXTAREA',
  SELECT = 'SELECT',
  DATE = 'DATE',
  NUMBER = 'NUMBER',
  BUTTON = 'BUTTON',
  PANEL = 'PANEL',
  TABLE = 'TABLE',
  LAYOUT_EXTEND = 'LAYOUT_EXTEND',
  HEADING = 'HEADING',
  TEXT = 'TEXT',
  FILE = 'FILE',
  TABS = 'TABS',
  STEPS = 'STEPS',
  EDITOR = 'EDITOR',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  FLOATING_LABEL = 'FLOATING_LABEL',
  SWITCH = 'SWITCH',
  OZEFORM = 'OZEFORM',
  HTML = 'HTML'
}
export enum TYPE_ACTION_EVENT {
  CONDITION = 'CONDITION',
  LOGOUT = 'LOGOUT',
  NAVIGATE = 'NAVIGATE',
  SLEEP = 'SLEEP',
  SHOW_MODAL = 'SHOW_MODAL',
  API_CONNECTOR = 'API_CONNECTOR',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  END = 'END',
  START = 'START',
  HIDDEN = 'HIDDEN',
  READONLY = 'READONLY',
  SCRIPT = 'SCRIPT',
  GET_VALUE = 'GET_VALUE',
  SET_VALUE = 'SET_VALUE',
  SET_OPTIONS_SELECT = 'SET_OPTIONS_SELECT',
  LAYOUT = 'LAYOUT',
  DECISION = 'DECISION'
}

export enum TYPE_ACTION_TASK {
  SUBMIT = 'SUBMIT',
  CANCEL = 'CANCEL',
  RETURN = 'RETURN',
  REJECT = 'REJECT',
  APPROVE = 'APPROVE'
}
export enum SYSTEM_CLIENT_SERVICE {
  DEFAULT = 'defaultservice',
  TASK_DETAIL = 'system-svc-taskdetail'
}
